"""empty message

Revision ID: bb3bee222b9d
Revises: a92a18679f62
Create Date: 2022-07-25 20:48:58.859630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3bee222b9d'
down_revision = 'a92a18679f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('reservation', sa.Column('customer_phone', sa.String(), nullable=True))
    op.drop_column('reservation', 'owner_name')
    op.drop_column('reservation', 'owner_tel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('owner_tel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('owner_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reservation', 'customer_phone')
    op.drop_column('reservation', 'customer_name')
    # ### end Alembic commands ###
